language: php

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - hhvm
  
matrix:
  fast_finish: true
  allow_failures:
    - php: hhvm
    - php: 7.0

before_script:
  - composer self-update
  - composer update

script:
  - mkdir -p build/logs
  - vendor/bin/phpunit
  - vendor/bin/phpcs --standard=PSR2 src/ test/

after_script:
  - sh .travis.coverage.sh
  - vendor/bin/phpmd src/ text codesize,design,naming,unusedcode
