language: php

php:
  - 5.4
  - 5.5

before_script:
  - composer self-update
  - composer update --prefer-source --dev

script:
  - ./vendor/bin/phpunit --coverage-clover ./build/logs/clover.xml
  - ./vendor/bin/phpcs --standard=PSR2 ./src/ ./test/

#after_script:
#  - php vendor/bin/coveralls -v
