language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm
  
matrix:
  fast_finish: true
  allow_failures:
    - php: hhvm

before_script:
  - composer self-update
  - composer install --dev --prefer-source

script:
  - mkdir -p build/logs
  - vendor/bin/phpunit
  - vendor/bin/phpcs --standard=PSR2 src/ test/

after_script:
  - sh .travis.coverage.sh
  - vendor/bin/phpmd src/ text cleancode,codesize,controversial,design,naming,unusedcode
